# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Gradle Build Action
      # You may pin to the exact commit or the version.
      # uses: gradle/gradle-build-action@bebb162342333983b660d21f31c90f33950f5023
        uses: gradle/gradle-build-action@v2.0-beta.1
        with:
          # Path to the root directory of the build
          build-root-directory: project
          # Gradle command line arguments, see gradle --help
          arguments: 'createEpub'

      - name: Purge artifacts
      # You may pin to the exact commit or the version.
      # uses: kolpav/purge-artifacts-action@04c636a505f26ebc82f8d070b202fb87ff572b10
        uses: kolpav/purge-artifacts-action@v1
        with:
          # Human readable expire duration
          expire-in: 7days
          # Github auth token
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: book
          path: build/*.epub
